<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

class TeamRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name' => 'required|string|min:3|max:200',
            'name_en' => 'required|string|min:3|max:200|unique:teams,name_en',
            'image' => ($this->method() === 'POST' ? 'required|' : '') . 'image',
        ];
    }

    public function attributes()
    {
        return [
            'name' => 'Arabic Name',
            'name_en' => 'English Name',
            'image' => 'Logo'
        ]; // TODO: Change the autogenerated stub
    }
}
